/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package land.melty.matrixappserviceqq

import kotlinx.coroutines.runBlocking
import net.mamoe.mirai.BotFactory
import net.mamoe.mirai.alsoLogin
import net.mamoe.mirai.event.events.GroupMessageEvent
import net.mamoe.mirai.message.data.MessageSource.Key.quote
import net.mamoe.mirai.message.data.content
import net.mamoe.mirai.utils.BotConfiguration.MiraiProtocol.ANDROID_PAD

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>): Unit = runBlocking {
    val qqid: Long = args[0].toLong()
    val bot = BotFactory.newBot(qqid, args[1]) {
        fileBasedDeviceInfo()
        protocol = ANDROID_PAD
    }.alsoLogin()
    bot.eventChannel.subscribeAlways<GroupMessageEvent> {
        println(message.content)
    }
}
